name: ${pluginName}
main: vg.civcraft.mc.citadel.Citadel
version: ${version}
authors:
- Rourke750
- Maxopoly
- ProgrammerDan
- okx-code
- Cranite
- FeatherCrown
- Lazersmoke
- TealNerd
- Scuwr
- Diet-Cola
- Aleksey-Terzi
depend:
- NameLayer
- CivModCore
softdepend:
- HolographicDisplays
description: ${description}
api-version: ${api_version}
permissions:
  citadel.admin:
    default: op
